export const costumeList = [
    "Vampire",
    "Werewolf",
    "Frankenstein's Monster",
    "Mummy",
    "Ghost",
    "Witch",
    "Zombie",
    "Skeleton",
    "Pumpkin Head",
    "Demon",
    "Bat",
    "Grim Reaper",
    "Scarecrow",
    "Invisible Man",
    "Mad Scientist",
    "Freddy Krueger",
    "Jason Voorhees",
    "Michael Myers",
    "Pennywise the Clown",
    "Chucky",
    "Leatherface",
    "Ghostface (Scream)",
    "Predator",
    "Hannibal Lecter",
    "Spatula",
    "Baked Potato",
    "Nerd",
    "Siamese Twins",
    "Toaster",
    "Upside-Down Person",
    "Ceiling Fan ('Go Ceilings!')",
    "Cactus",
    "Human Disco Ball",
    "Traffic Cone",
    "Surge Protector",
    "Cloud with Lightning Bolts",
    "Christmas Tree",
    "SpongeBob SquarePants",
    "Patrick Star",
    "Michelangelo (Ninja Turtles)",
    "Iron Man",
    "Spider-Man",
    "Hulk",
    "Captain America",
    "Deadpool",
    "Groot",
    "Harley Quinn",
    "Batman",
    "Joker",
    "Elsa",
    "Ash Ketchum",
    "Donald Trump",
    "P Diddy",
    "Weird Al Yankovic",
    "Neil DeGrasse Tyson",
    "Joe Rogan",
    "Taylor Swift",
    "Harry Styles",
    "Kanye West",
    "Kim Kardashian",
    "Beyoncé",
    "Miley Cyrus",
    "Elon Musk",
    "Mark Zuckerberg",
    "Barbie",
    "Oppenheimer",
    "Cryptocurrency Miner",
    "Astronaut",
    "A QR Code (scan to trick-or-treat)",
    "Giant Banana",
    "Hot Dog",
    "Pickle Rick",
    "A Sim with the green diamond",
    "Inflatable Dinosaur",
    "80s Aerobics Instructor",
    "Bee Keeper",
    "Chef with Giant Spaghetti Pot",
    "Viking",
    "Knight in Shining Armor",
    "Space Cowboy",
    "David Bowie"
]
